name       : glances
version    : 2.7.1
release    : 12
source     :
    - https://github.com/nicolargo/glances/archive/v2.7.tar.gz : 8aa40c1c2f0114686ccd1619168c629ee18abfa2b5a1b26bf9f4c16a367e76fd
license    : LGPL-3.0
summary    : CLI curses-based monitoring tool
component  : system.utils
description: |
    CLI curses-based monitoring tool
builddeps  :
    - python-setuptools
rundeps    :
    - python-psutil
    - python-setuptools
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
