name       : glances
version    : 3.2.4.2
release    : 35
source     :
    - https://github.com/nicolargo/glances/archive/refs/tags/v3.2.4.2.tar.gz : 88ac8103d777b2a55cee9418a5940269c640c3ad964ec44de0e9bb80cdbead37
homepage   : https://nicolargo.github.io/glances/
license    : LGPL-3.0-or-later
component  : system.utils
summary    : Glances is a cross-platform system monitoring tool written in Python
description: |
    Glances is a cross-platform monitoring tool which aims to present a large amount of monitoring information through a curses or Web based interface. The information dynamically adapts depending on the size of the user interface.
builddeps  :
    - python-defusedxml
    - python-psutil
rundeps    :
    - python-bottle
    - python-defusedxml
    - python-future
    - python-packaging
    - python-psutil
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc/glances/{AUTHORS,CONTRIBUTING.md,COPYING,NEWS.rst,README.rst}
check      : |
    %python3_test
