name       : glances
version    : 3.1.4
release    : 29
source     :
    - https://github.com/nicolargo/glances/archive/v3.1.4.tar.gz : bf5ec080b824f724bc2a5a42b6e2dbe9eba3effd60d50f2cf39af7e9bf18f6b7
homepage   : https://nicolargo.github.io/glances/
license    : LGPL-3.0-only
summary    : CLI curses-based monitoring tool
component  : system.utils
description: |
    Glances is a cross-platform monitoring tool which aims to present a large amount of monitoring information through a curses or Web based interface. The information dynamically adapts depending on the size of the user interface.
rundeps    :
    - python-future
    - python-psutil
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc/glances/{AUTHORS,CONTRIBUTING.md,COPYING,NEWS.rst,README.rst}
