name       : glances
version    : 2.9.1
release    : 19
source     :
    - https://github.com/nicolargo/glances/archive/v2.9.1.tar.gz : f661554a38101b84a4e3eb6980971a4e161e63ddf5eca68df6ee8b4576100985
license    : LGPL-3.0
summary    : CLI curses-based monitoring tool
component  : system.utils
description: |
    CLI curses-based monitoring tool
builddeps  :
    - python-setuptools
rundeps    :
    - python-psutil
    - python-setuptools
install    : |
    %python_install
