name       : glances
version    : 2.8.2
release    : 16
source     :
    - https://github.com/nicolargo/glances/archive/v2.8.2.tar.gz : 869fbb090581eb91219b440fdeaada9164f0912494942ea41c7f057350472bf8
license    : LGPL-3.0
summary    : CLI curses-based monitoring tool
component  : system.utils
description: |
    CLI curses-based monitoring tool
builddeps  :
    - python-setuptools
rundeps    :
    - python-psutil
    - python-setuptools
install    : |
    %python_install
