name       : glances
version    : 3.1.2
release    : 26
source     :
    - https://github.com/nicolargo/glances/archive/v3.1.2.tar.gz : adda21ceaff7a04b18b0f71f2dbfcc1647bd0aa888d12f61f1e03f4f60216a12
license    : LGPL-3.0-only
summary    : CLI curses-based monitoring tool
component  : system.utils
description: |
    CLI curses-based monitoring tool
rundeps    :
    - python-future
    - python-psutil
install    : |
    %python3_install
