name       : glances
version    : 2.4.2
release    : 5
source     :
    - https://github.com/nicolargo/glances/archive/v2.4.2.tar.gz : 725e8d15e8347e5371e3b8c7c3e9f2e3c8389dd847f01a693ceae8c910d1b97c
license    : LGPL-3.0
summary    : CLI curses-based monitoring tool
description: |
    CLI curses-based monitoring tool
builddeps  :
    - python-setuptools
rundeps    :
    - python-psutil
    - python-setuptools
setup      : |
build      : |
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
