name       : glances
version    : 2.5.1
release    : 7
source     :
    - https://github.com/nicolargo/glances/archive/v2.5.1.tar.gz : 814cea926c4d491487c06d7ce8d178d412c6223ea3aff03085cba8118c8e8a3d
license    : LGPL-3.0
summary    : CLI curses-based monitoring tool
description: |
    CLI curses-based monitoring tool
builddeps  :
    - python-setuptools
rundeps    :
    - python-psutil
    - python-setuptools
setup      : |
build      : |
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
