name       : glances
version    : 3.0.2
release    : 23
source     :
    - https://github.com/nicolargo/glances/archive/v3.0.2.tar.gz : 76a793a8e0fbdce11ad7fb35000695fdb70750f937db41f820881692d5b0a29c
license    : LGPL-3.0-only
summary    : CLI curses-based monitoring tool
component  : system.utils
description: |
    CLI curses-based monitoring tool
rundeps    :
    - python-psutil
install    : |
    %python3_install
