name       : glances
version    : 3.1.1
release    : 25
source     :
    - https://github.com/nicolargo/glances/archive/v3.1.1.tar.gz : 2fd826d39ed77bcc3656dfff15b4cb3613de9caae0f8e26bd578913110e189fb
license    : LGPL-3.0-only
summary    : CLI curses-based monitoring tool
component  : system.utils
description: |
    CLI curses-based monitoring tool
rundeps    :
    - python-future
    - python-psutil
install    : |
    %python3_install
