name       : glances
version    : '2.11'
release    : 21
source     :
    - https://github.com/nicolargo/glances/archive/v2.11.tar.gz : 12fedb4b39a23e8b7d175696231e9ae765efe9f633946d21135a98a13d3a29e7
license    : LGPL-3.0
summary    : CLI curses-based monitoring tool
component  : system.utils
description: |
    CLI curses-based monitoring tool
builddeps  :
    - python-setuptools
rundeps    :
    - python-psutil
    - python-setuptools
install    : |
    %python_install
