name       : glances
version    : 2.6
release    : 8
source     :
    - https://github.com/nicolargo/glances/archive/v2.6.tar.gz : 71970e774dc8c58d67388579482153d304b057498e7db14f9cbfa8ac483ce78b
license    : LGPL-3.0
summary    : CLI curses-based monitoring tool
description: |
    CLI curses-based monitoring tool
builddeps  :
    - python-setuptools
rundeps    :
    - python-psutil
    - python-setuptools
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
