name       : glances
version    : 2.11.1
release    : 22
source     :
    - https://github.com/nicolargo/glances/archive/v2.11.1.tar.gz : 446a0ee6e13c0c7ceb4bc0d4868add8a02d5e3ff866de8e880bdb33dce6ab3fc
license    : LGPL-3.0
summary    : CLI curses-based monitoring tool
component  : system.utils
description: |
    CLI curses-based monitoring tool
builddeps  :
    - python-setuptools
rundeps    :
    - python-psutil
    - python-setuptools
install    : |
    %python_install
