name       : glances
version    : 2.8.6
release    : 18
source     :
    - https://github.com/nicolargo/glances/archive/v2.8.6.tar.gz : 952fbd1aabe6d05dd8f0f7035c5f3aab531fe8753fdf5b46c1198e5a3d29019b
license    : LGPL-3.0
summary    : CLI curses-based monitoring tool
component  : system.utils
description: |
    CLI curses-based monitoring tool
builddeps  :
    - python-setuptools
rundeps    :
    - python-psutil
    - python-setuptools
install    : |
    %python_install
