name       : glances
version    : 3.1.4.1
release    : 30
source     :
    - https://github.com/nicolargo/glances/archive/v3.1.4.1.tar.gz : 0347a0b949451fd0022c0f22e54092fe526120a776af1f2bde1ea7ba61d6b792
homepage   : https://nicolargo.github.io/glances/
license    : LGPL-3.0-only
summary    : Glances is a cross-platform system monitoring tool written in Python
component  : system.utils
description: |
    Glances is a cross-platform monitoring tool which aims to present a large amount of monitoring information through a curses or Web based interface. The information dynamically adapts depending on the size of the user interface.
rundeps    :
    - python-future
    - python-psutil
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc/glances/{AUTHORS,CONTRIBUTING.md,COPYING,NEWS.rst,README.rst}
