name       : glances
version    : 3.1.0
release    : 24
source     :
    - https://github.com/nicolargo/glances/archive/v3.1.0.tar.gz : 56e67aee5960ecb575a7277e87b06d305ec87d2108f65860d13d9111d320bdf5
license    : LGPL-3.0-only
summary    : CLI curses-based monitoring tool
component  : system.utils
description: |
    CLI curses-based monitoring tool
rundeps    :
    - python-psutil
install    : |
    %python3_install
