name       : glances
version    : 2.5
release    : 6
source     :
    - https://github.com/nicolargo/glances/archive/v2.5.tar.gz : 352d863d115870f0823203ffe29119f3ebfa12236b76af525e920356f822cad0
license    : LGPL-3.0
summary    : CLI curses-based monitoring tool
description: |
    CLI curses-based monitoring tool
builddeps  :
    - python-setuptools
rundeps    :
    - python-psutil
    - python-setuptools
setup      : |
build      : |
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
