name       : glances
version    : 2.4.1
release    : 4
source     :
    - https://codeload.github.com/nicolargo/glances/tar.gz/v2.4.1 : 827ab6e1ab94922c98bff4c531d484b8ed566ebe8f4d72f63eb78dc01743af8b
license    : LGPL-3.0
summary    : CLI curses-based monitoring tool
description: |
    CLI curses-based monitoring tool
builddeps  :
    - python-setuptools
rundeps    :
    - python-psutil
    - python-setuptools
setup      : |
build      : |
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
