name       : glances
version    : 2.8.1
release    : 15
source     :
    - https://github.com/nicolargo/glances/archive/v2.8.1_1.tar.gz : 6fd0a3e3165c458668d011a30060e76342f4222f2a7b344d6d665eb058c01ab0
license    : LGPL-3.0
summary    : CLI curses-based monitoring tool
component  : system.utils
description: |
    CLI curses-based monitoring tool
builddeps  :
    - python-setuptools
rundeps    :
    - python-psutil
    - python-setuptools
install    : |
    %python_install
