name       : glances
version    : 3.1.6.1
release    : 33
source     :
    - https://github.com/nicolargo/glances/archive/v3.1.6.1.tar.gz : 1ce97928f50906ece665b41ea854c1129540592fd48bed2eade0cd31189692e2
homepage   : https://nicolargo.github.io/glances/
license    : LGPL-3.0-only
component  : system.utils
summary    : Glances is a cross-platform system monitoring tool written in Python
description: |
    Glances is a cross-platform monitoring tool which aims to present a large amount of monitoring information through a curses or Web based interface. The information dynamically adapts depending on the size of the user interface.
rundeps    :
    - python-bottle
    - python-future
    - python-psutil
install    : |
    %python3_install
    rm -rf $installdir/usr/share/doc/glances/{AUTHORS,CONTRIBUTING.md,COPYING,NEWS.rst,README.rst}
